sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.13.0

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: java

before_install:
  # Update Docker.
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

  # Upgrade/install docker-compose.
  - sudo rm -f /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  # Print out the current docker-compose version.
  - docker-compose --version

script:
  # Build
  - mvn clean install -Pfull | grep -v 'Download.* http'
  # Integrations tests
  - sudo logisland-docker/src/integration-test/run-all-test.sh

jdk:
  - oraclejdk8

install:
  - sudo sysctl -w vm.max_map_count=262144

notifications:
  email:
    - bailet.thomas@gmail.com
    - s.h.gregoire@gmail.com

  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e305a73a60a02fefba40
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always




