sudo: required
dist: trusty

#services:
#  - docker

#env:
#  DOCKER_COMPOSE_VERSION: 1.13.0

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: java

before_install:
  - sudo mkdir -p /usr/local/share/java/opencv4/
  - wget https://github.com/Hurence/logisland/releases/download/v1.2.0/libopencv_java411.so
  - wget https://github.com/Hurence/logisland/releases/download/v1.2.0/opencv-411.jar
  - sudo mv libopencv_java411.so /usr/local/share/java/opencv4/
  - sudo mv opencv-411.jar /usr/local/share/java/opencv4/
  - sudo chmod 755 /usr/local/share/java/opencv4/*
  - mvn install:install-file -Dfile=opencv-411.jar -DgroupId=opencv -DartifactId=opencv -Dversion=4.1.1 -Dpackaging=jar

#
#  # Upgrade/install docker-compose.
#  - sudo rm -f /usr/local/bin/docker-compose
#  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
#  - chmod +x docker-compose
#  - sudo mv docker-compose /usr/local/bin
#  # Print out the current docker-compose version.
#  - docker-compose --version

script:
  # Build
  # use travis_wait so it does not time_out after 10 minutes without output (unfortunately that seems to not work)
  # use -q so there's not too much output for travis (4Mb max)
  - travis_wait mvn clean install -Pintegration-tests -q
  # build assembly (there is currently missing jars in assembly when using mvn clean install...)
  - mvn clean package -DskipTests -q
  # Integrations tests
  - sudo logisland-docker/src/integration-test/run-all-test.sh

jdk:
  - openjdk8

install:
  - sudo sysctl -w vm.max_map_count=262144

notifications:
  email:
    - bailet.thomas@gmail.com
    - s.h.gregoire@gmail.com
    - mathieu.rossignol@hurence.com 

  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e305a73a60a02fefba40
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always




