apiVersion: v1
kind: Service
metadata:
  name: chronix-headless
  namespace: logisland
spec:
  #clusterIP: None
  ports:
    - name: solr
      port: 8983
      protocol: TCP
      targetPort: 8983
  selector:
    app: chronix
  sessionAffinity: None
  type: ClusterIP