apiVersion: v1
kind: Pod
metadata:
  name: kafka-test-client
  namespace: logisland
spec:
  containers:
    - command:
        - sh
        - -c
        - exec tail -f /dev/null
      image: confluentinc/cp-kafka:4.1.2-2
      imagePullPolicy: IfNotPresent
      name: kafka
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File