version: "2"
services:

  zookeeper:
#    container_name: zookeeper
    image: hurence/zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"

  kafka:
#    container_name: kafka
    image: hurence/kafka
    hostname: kafka
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_JMX_PORT: 7071

  # Logisland container : which does the test
  logisland:
    build: ../../../../../full-container
    command: /conf/test.sh
    links:
      - zookeeper
      - kafka
    ports:
      - "4050:4050"
      - "8082:8082"
      - "9999:9999"
    volumes:
      - .:/conf
      - ../../../docker-compose-shared-volume:/shared
#    environment:
#      KAFKA_ADVERTISED_PORT: 9092
#      KAFKA_ADVERTISED_HOST_NAME: kafka