version: '3'
services:

  zookeeper:
    image: hurence/zookeeper
    hostname: zookeeper
    ports:
      - '2181:2181'
    networks:
      - logisland

  kafka:
    image: hurence/kafka
    hostname: kafka
    ports:
      - '9092:9092'
    volumes:
      - kafka-home:/opt/kafka_2.11-0.10.0.1/
    environment:
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_JMX_PORT: 7071
    networks:
      - logisland

  # ES container
  # make sure to increase vm.max_map_count kernel setting like documented here :
  # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  elasticsearch:
    container_name: elasticsearch
    environment:
      - ES_JAVA_OPT='-Xms1G -Xmx1G'
      - cluster.name=es-logisland
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
    hostname: elasticsearch
    image: 'docker.elastic.co/elasticsearch/elasticsearch:5.4.0'
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - logisland

  # Kibana container
  kibana:
    container_name: kibana
    environment:
      - 'ELASTICSEARCH_URL=http://elasticsearch:9200'
    image: 'docker.elastic.co/kibana/kibana:5.4.0'
    ports:
      - '5601:5601'
    networks:
      - logisland


  # Logisland container : does nothing but launching
  logisland:
    container_name: logisland
    image: hurence/logisland:1.1.0
    command: tail -f bin/logisland.sh
    ports:
      - '4050:4050'
      - '8082:8082'
      - '9999:9999'
    volumes:
      - ./conf/logisland:/conf
      - ./data/logisland:/data
    networks:
      - logisland

  redis:
    container_name: redis
    image: 'redis:latest'
    ports:
      - '6379:6379'
    networks:
      - logisland

volumes:
  kafka-home:

networks:
  logisland:
