version: "2"
services:

  zookeeper:
    container_name: zookeeper
    image: hurence/zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: hurence/kafka
    hostname: kafka
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: sandbox
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_JMX_PORT: 7071

  # ES container
  # make sure to increase vm.max_map_count kernel setting like documented here :
  # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  elasticsearch:
    container_name: elasticsearch
    environment:
      - ES_JAVA_OPT="-Xms1G -Xmx1G"
      - cluster.name=es-logisland
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
    hostname: elasticsearch
    container_name: elasticsearch
    image: 'docker.elastic.co/elasticsearch/elasticsearch:5.4.0'
    ports:
      - '9200:9200'
      - '9300:9300'

  # Kibana container
  kibana:
    container_name: kibana
    environment:
      - 'ELASTICSEARCH_URL=http://elasticsearch:9200'
    image: 'docker.elastic.co/kibana/kibana:5.4.0'
    container_name: kibana
    links:
      - elasticsearch
    ports:
      - '5601:5601'

  # Logisland container : does nothing but launching
  logisland:
    container_name: logisland
    image: hurence/logisland:0.14.0
    command: tail -f bin/logisland.sh
    #command: bin/logisland.sh --conf /conf/index-apache-logs.yml
    links:
      - zookeeper
      - kafka
      - elasticsearch
      - redis
    ports:
      - "4050:4050"
    volumes:
      - ./conf/logisland:/conf
      - ./data/logisland:/data
    container_name: logisland
    extra_hosts:
      - "sandbox:172.17.0.1"

  redis:
    container_name: redis
    image: 'redis:latest'
    ports:
      - '6379:6379'
